
[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "github.com/slok/kubewebhook"
  version = "0.1.1"

[[constraint]]
  name = "github.com/controlplaneio/kubectl-kubesec"
  version = "0.3.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[prune]
  go-tests = true
  unused-packages = true
