apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubesec-webhook.fullname" . }}
  labels:
    app: {{ include "kubesec-webhook.name" . }}
    app.kubernetes.io/name: {{ include "kubesec-webhook.name" . }}
    helm.sh/chart: {{ include "kubesec-webhook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubesec-webhook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kubesec-webhook.name" . }}
        app.kubernetes.io/name: {{ include "kubesec-webhook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./kubesec
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-key-file=/etc/webhook/certs/key.pem
            - -min-score=0
            - -debug
          ports:
            - name: http
              containerPort: 80
              containerPort: 8080
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8081
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8081
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "kubesec-webhook.fullname" . }} 
